<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php /* @var $viewModel \Dmitriyprime\RelatedProductsList\ViewModel\RelatedProductsList */ ?>
<?php $viewModel = $block->getData('viewModel') ?>

<?php if ($viewModel->getProduct()->getTypeId() === 'simple'): ?>

<?php
if ($exist = $viewModel->getItems()->getSize()) {
    $type = 'related';
    $class = $type;
    $image = 'related_products_list';
    $items = $viewModel->getItems();
    $limit = 0;
    $shuffle = 0;
    $isWeightedRandom = 0;
    $showAddTo = true;
    $showCart = false;
    $description = false;
}
    $_item = null;
?>

<?php if ($exist): ?>

<div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
     data-shuffle="<?= /* @noEscape */
     $shuffle ?>"
     data-shuffle-weighted="<?= /* @noEscape */
     $isWeightedRandom ?>">
            <div class="block-title title">
                <strong id="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading" role="heading"
                        aria-level="2"><?= $escaper->escapeHtml(__('Related Products Custom')) ?></strong>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading">
                <div class="block-actions">
                    <?= $escaper->escapeHtml(__('Check items to add to the cart or')) ?>
                    <button type="button" class="action select"
                            data-role="select-all"><span><?= $escaper->escapeHtml(__('select all')) ?></span>
                    </button>
                </div>
                <div class="products wrapper grid products-grid products-<?= $escaper->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items">
                        <?php foreach ($items as $_item): ?>
                            <?php $available = ''; ?>
                            <?php if (
                                !$_item->isComposite() &&
                                $_item->isSaleable() &&
                                $type == 'related'
                            ): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if (!$_item->getCanNotShow()) : ?>
                                <li class="item product product-item"
                                    id="product-item_<?= /* @noEscape */
                                    $_item->getId() ?>"
                                    data-shuffle-group="<?= $escaper->escapeHtmlAttr($_item->getPriority()) ?>">
                                    <?= /* @noEscape */
                                    $secureRenderer->renderStyleAsTag(
                                        'display:none;',
                                        'li#product-item_' . $_item->getId()
                                    ) ?>
                                    <div class="product-item-info <?= /* @noEscape */
                                    $available ?>">
                                        <?= /* @noEscape */
                                        '<!-- ' . $image . '-->' ?>
                                        <a href="<?= $escaper->escapeUrl($viewModel->getProductUrl($_item)) ?>"
                                           class="product photo product-item-photo">
                                            <?= $viewModel->getImage($_item, $image)->toHtml() ?>
                                        </a>
                                        <div class="product details product-item-details">

                                            <strong class="product name product-item-name"><a
                                                    class="product-item-link"
                                                    title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                                    href="<?= $escaper->escapeUrl($viewModel->getProductUrl($_item)) ?>">
                                                    <?= $escaper->escapeHtml($_item->getName()) ?></a>
                                            </strong>

                                            <?= /* @noEscape */
                                            $viewModel->getProductPrice($_item) ?>

                                            <?php if (!$_item->isComposite() && $_item->isSaleable()
                                                && $type == 'related'): ?>
                                                <?php if (!$_item->getRequiredOptions()): ?>
                                                    <div class="field choice related">
                                                        <input
                                                            type="checkbox"
                                                            class="checkbox related"
                                                            id="related-checkbox<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"
                                                            name="related_products[]"
                                                            value="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>"/>
                                                        <label class="label"
                                                               for="related-checkbox<?= $escaper->escapeHtmlAttr($_item->getId())
                                                               ?>"><span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                        </label>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>

                                        </div>
                                    </div>
                                </li>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
